model_list:
  - model_name: gpt-35-turbo
    litellm_params:
      model: azure/gpt-35-turbo
      api_base: os.environ/AZURE_OPENAI_ENDPOINT_GPT
      api_key: os.environ/AZURE_OPENAI_API_KEY_GPT
      api_version: "2023-03-15-preview"
